<?php
/**
 * Created by PhpStorm.
 * User: elm
 * Date: 8/31/17
 * Time: 10:44 AM
 */
defined('_JEXEC') or die('Restricted access');

class DonateViewDonate extends JViewLegacy{

    function display($tpl = null)
    {
        $document = JFactory::getDocument();
        $document->addStyleSheet('components/com_donate/scripts/custom.css');
/*        $document->addStyleSheet('components/com_donate/scripts/bootstrap/css/bootstrap.css');*/
        /*$document->addCustomTag('<link href="components/com_donate/scripts/custom.css" type="text/css"/>');*/
        $document->addCustomTag('<script src="components/com_donate/scripts/jquery.min.js"></script>');
        $document->addCustomTag('<script src="components/com_donate/scripts/bootstrap/js/bootstrap.js"></script>');
        $document->addCustomTag('<script src="components/com_donate/scripts/vue.js"></script>');
        $document->addCustomTag('<script src="components/com_donate/scripts/app.js" defer></script>');
        return parent::display($tpl); // TODO: Change the autogenerated stub
    }
}