<?php
/**
 * @package     ${NAMESPACE}
 * @subpackage
 *
 * @copyright   A copyright
 * @license     A "Slug" license name e.g. GPL2
 */
defined('_JEXEC') or die('Restricted access');

class DonateViewCompleted extends JViewLegacy{
    function display($tpl = null)
    {
        $document = JFactory::getDocument();
        $document->addCustomTag('<link href="components/com_donate/scripts/bootstrap/css/bootstrap.css" type="text/css"/>');
        $document->addCustomTag('<script src="components/com_donate/scripts/jquery.min.js"></script>');
        $document->addCustomTag('<script src="components/com_donate/scripts/bootstrap/js/bootstrap.js"></script>');
        $document->addCustomTag('<script src="components/com_donate/scripts/vue.js"></script>');
        $document->addCustomTag('<script src="components/com_donate/scripts/vue-router.js"></script>');
        $document->addCustomTag('<script src="components/com_donate/scripts/app.js" defer></script>');
        return parent::display($tpl); // TODO: Change the autogenerated stub
    }
}